### ISSUE TITLE
Send SMS to add to Notion?

### ISSUE THREAD

**Issue by secretlycarl** [kevinjalbert/ama#4]
Hello Kevin, first I'd like to thank you for your Notion + Google assistant guide. Great stuff! 
As I was looking through it, I got an idea. What if, instead of using Google assistant to add to Notion, you could send a text to a certain number to accomplish the same thing? Perhaps with some tags to put it into different pages depending on the type of content it is. Do you think this is possible without an API?

**Comment by kevinjalbert** [comment]
Hey @secretlycarl,

I'm glad you enjoyed the content I produced!

> What if, instead of using Google assistant to add to Notion, you could send a text to a certain number to accomplish the same thing?

This is 100% doable, although it would require some custom work to make it function as expected. [IFTTT doesn't support SMS (text messages) anymore](https://help.ifttt.com/hc/en-us/articles/360023055054-Important-changes-to-the-SMS-service), and [Zapier only uses SMS to _send_ information](https://zapier.com/apps/sms). You'll likely have to set up an SMS service (e.g., [Twilio](https://www.twilio.com/sms/api)), then connect it somehow to your web server (e.g., [`notion-heroku`](https://github.com/kevinjalbert/notion-heroku)) to then add stuff to your Notion.

Overall, it's likely a lot of work.

> Do you think this is possible without an API?

Yes as you can use the unofficial Notion API like [`notion-py`](https://github.com/jamalex/notion-py).

-----

I wish you the best of luck if you are going to attempt this :). Let me know how it goes.
