### ISSUE TITLE
saying hi + still using notion?

### ISSUE THREAD

**Issue by andrewmcodes** [kevinjalbert/ama#5]
Hey Kevin,

Was participating in my standard blogging activity of bike shedding on my website instead of writing and finally got sick of the endless cycle. 

After lots of googling and dismay at what others are doing I stumbled back on notion and eventually here. 

My question is are you still using notion? 

More importantly, are you satisfied with it or is there something else you are eyeing? 

Thanks!

**Comment by kevinjalbert** [comment]
Hello @andrewmcodes,

I'm still using Notion, although for the better part of 2020 my usage dropped a lot. Mainly as I was on parental leave.

I'm still working away on improving my Notion setup. I use to use a [weekly template](https://kevinjalbert.com/my-weekly-notion-setup/), although I've abandoned that at this point. For the most part, I like Notion and for what it provides I cannot find anything that replaces it for me.

I'm still waiting to see how the official API looks, but in the meantime, I've been [working on my own API using the unofficial one](https://github.com/kevinjalbert/notion-toolbox/tree/master/server).

**Comment by andrewmcodes** [comment]
@kevinjalbert Thanks for responding!
